### ISSUE TITLE
Incompatible with Zevac’s Survival Flight Mod

### ISSUE THREAD

**Issue by mahilo3550** [iamshift/MineAddons2#1]
MC: 1.12.2 Forge: 14.23.2.2654 Mine Addons: 2.1 & 2.2  Zevac’s Survival Flight: 0.1.11

Installing this mod locks survival flight as disabled. Pressing the set keybinding does nothing when it should be toggling back and forth from enabled to disabled.

**Comment by shiftthedev** [comment]
i will look into

**Comment by shiftthedev** [comment]
fixed in v2.3
