### ISSUE TITLE
iSheep and ZombieLlama Hitbox Broken

### ISSUE THREAD

**Issue by Jo-Mamma75** [iamshift/MineAddons2#2]
Could not attack and/or kill iSheep or ZombieLlama in latest version (MineAddons-v2.6-mc1.12.2.jar).

**Comment by Jo-Mamma75** [comment]
I didn't actually experience this.  I was just reporting it because it was reported to me.  We are in the development of FoolCraft 3.  Iskall ran into one in the nether that he couldn't hit and died to it.  He had Scalda come and try and he also died.  No idea what actually happened.

**Comment by IRicTheCoder** [comment]
@Jo-Mamma75 We have tested this in our private server and I can attest that the Hitbox are present and you can attack and kill all mobs added by MineAddons.

I would suggest you look into the mods in the modpack to see if some could be altering in some way the Hitbox of the mobs. Also another suggestion I can give you is to see in the log when someone attacks one of those mobs if it displays some error or warning.

**Comment by Jo-Mamma75** [comment]
Well I'm going to go ahead and close this issue.  Could always be a case of a couple of players being morons.  Who knows?
