### ISSUE TITLE
[Suggestion] Add Config Options to Enable/Disable Individual Items and/or Sections

### ISSUE THREAD

**Issue by Jo-Mamma75** [iamshift/MineAddons2#3]
It would be cool to have the ability to individually enable or disable certain sections of the mod or individual items/entities within the mod.

**Comment by IRicTheCoder** [comment]
@Jo-Mamma75 All things in the mod are Interconnected, meaning that you can't remove one without breaking most things, so having the option to disable stuff wouldn't be something possible to do. Something like disabling the mobs from spawning (which will be implemented in 2.7) should work, more things besides this isn't that possible.

The tinkers addon will also have a config to disable it.

I would say that certain items can be deactivates by simply removing their recipe using CraftTweaker.
