### ISSUE TITLE
[1.12.2] Is it intended for Creepiers to spawn in Mushroom Island / Shore Biomes?

### ISSUE THREAD

**Issue by SonicX8000** [iamshift/MineAddons2#6]
Normally hostiles can't spawn in Mushroom Island / Shore unless defined by something to force them to spawn but apparently these mobs are the only ones to spawn in these biomes. No other hostiles from other mods do this as far as I know.

Well... maybe mobs do spawn in Mushroom Island Shore biomes but certainly the Mushroom Island biome itself prevents that as only Mooshrooms spawn in them.

**Comment by shiftthedev** [comment]
They shouldn't spawn there anymore in version 2.10.

**Comment by SonicX8000** [comment]
It appears they no longer spawn in Mushroom Island / Shore biomes now in v2.1.0. If anything else comes up I'll let you know. Thank you.
