### ISSUE TITLE
[1.12.2] Bonus Damage on Harmonious Bow Materials suppose to be 100?

### ISSUE THREAD

**Issue by SonicX8000** [iamshift/MineAddons2#7]
It has a drawspeed of 0.08 and 5 range multiplier but a massive 100 Bonus Damage which kinda seems to be on the high side.

That reminds me... I recall there being Fiberglass Materials for Bow-like Tools but they were removed in later versions. Don't think they had high bonus damage but they were fast on their drawspeed, faster than Harmonious.

Just figure it's a choice if you wanted more damage but less speed or more speed but lass damage although 100 seems a bit too high.

**Comment by shiftthedev** [comment]
The stats were wrong.
It's fixed in 2.10.
