### ISSUE TITLE
JEI OR NEI No Recipes

### ISSUE THREAD

**Issue by TorinnTheDragon** [iamshift/MineAddons2#8]
I don't know if its their issue or not, but there is no recipes to make any of the upgraded armors, like infused diamond, ultimate armor, or the upgraded ultimate armor in JEI or NEI.  Version I'm using is V.2.9. And the wiki doesn't show how to make the upgraded ultimate armor.

**Comment by shiftthedev** [comment]
something broke with JEI updates. but I added the info to wiki.
https://github.com/iamshift/MineAddons2/wiki/Fiberglass-(Tinkers'-Addon)#upgraded-ultimate-armor

**Comment by TorinnTheDragon** [comment]
> 
> 
> something broke with JEI updates. but I added the info to wiki.
> https://github.com/iamshift/MineAddons2/wiki/Fiberglass-(Tinkers'-Addon)#upgraded-ultimate-armor

Thanks for updating the wiki, and one last thing was to put how make the liquid Harmonious on there as well. But that should do it for me thanks 👍

**Comment by shiftthedev** [comment]
Thanks for the heads-up. I added the info on Liquid Harmonious to the wiki too.
